config/routes.rb
Rails.application.routes.draw do

  resources :reviews

  resources :contacts

  get 'white/index'

  devise_for :installs
  resources :orders do
  resources :orderitems
  end
  
  devise_for :users do
  resources :orders
  end
  

  get 'orderitems/index'

  get 'orderitems/show'

  get 'orderitems/new'

  get 'orderitems/edit'

  resources :profiles

  get 'review/index'
  get 'review/show'
  get 'review/new'
  get 'review/edit'

  resources :reviews


get '/home' =>'home#index'
get '/red' => 'red#index'
get '/white' => 'white#index'
get '/contact' => 'site#contact'
get '/myprofile' => 'profiles#myprofile' 
get '/about' => 'site#about'
get '/contact' => 'site#contact'
get '/Admin'=> 'user#admin_login'
get '/payment' => 'cart#payment'
get '/cart' => 'cart#index'
get '/cart/clear' => 'cart#clearCart'
get '/cart/:id' => 'cart#add'
get '/cart/remove/:id' => 'cart#remove'
get '/checkout' => 'cart#createOrder'
resources :items


# config/routes.rb
get "/404", :to => "errors#not_found"
get "/422", :to => "errors#unacceptable"
get "/500", :to => "errors#internal_error"


 root :to => 'home#index'
  
end

app/models/contact.rb
class Contact < ActiveRecord::Base
end

app/models/install.rb
class Install < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/item.rb
class Item < ActiveRecord::Base
	has_many :reviews
end

app/models/order.rb
class Order < ActiveRecord::Base
  has_many :orderitems
  belongs_to :user
end

app/models/orderitem.rb
class Orderitem < ActiveRecord::Base
  belongs_to :order
end

app/models/profile.rb
class Profile < ActiveRecord::Base
  belongs_to :user
end

app/models/review.rb
class Review < ActiveRecord::Base


  belongs_to :item

  	


end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

     has_many :orders   
     has_one :profile
     has_many :reviews
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_filter :authenticate_user!
before_filter :ensure_admin, :only => [:destroy]

  def ensure_admin
  unless current_user && current_user.admin?
  render:text => "Access Error", :status => :unauthorized
  end
  end 

  respond_to :html

  def myprofile
     profile = Profile.find_by_user_id(current_user.id)
     
    if profile.nil?
      redirect_to "/profiles/new"
    else
      @user = User.find(current_user.id)
      @profile = Profile.find_by_user_id(@user.id)
      redirect_to "/items"
    end
  end

  
  def index
    @profiles = Profile.all
    respond_with(@profiles)
  end

  def show
    respond_with(@profile)
  end

  def new
    @user = User.find(current_user.id)
  @profile = Profile.new
    @profile.user_id = @user.id
    respond_with(@profile)
  end

  def edit
  end

  def create
    @profile = Profile.new(profile_params)
    @profile.save
    respond_with(@profile)
  end

  def update
    @profile.update(profile_params)
    respond_with(@profile)
  end

  def destroy
    @profile.destroy
    respond_with(@profile)
  end

  private
    def set_profile
      @profile = Profile.find(params[:id])
    end

    def profile_params
      params.require(:profile).permit(:firstname, :lastname, :address, :mobile, :user_id)
    end
end

app/controllers/red_controller.rb
class RedController < ApplicationController

before_filter :authenticate_user!
before_filter :ensure_admin, :only => [:new, :create, :edit, :destroy]
before_action :set_item, only: [:show, :edit, :update,:destroy]
  def ensure_admin
  unless current_user && current_user.admin?
  render:text => "Access Error", :status => :unauthorized
  end
  end 

  def index
     @items = Item.where(category: 'Red')
  end

  

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def item_params
      params.require(:item).permit(:name, :price, :description, :image_ur, :img_url_big, :category)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_helper.rb
module CartHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/orderitems_helper.rb
module OrderitemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/red_helper.rb
module RedHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper

	
end

app/helpers/session_helper.rb
module SessionHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/white_helper.rb
module WhiteHelper
end

app/views/profiles/_form.html.erb
<div style="width:300px; margin:30px auto; background:#f5f5f5; padding:20px" class="text-center ">


<%= form_for(@profile) do |f| %>
  <% if @profile.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@profile.errors.count, "error") %> Please correct the error!</h2>

      <ul>
      <% @profile.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :firstname %><br>
    <%= f.text_field :firstname, :required => true %>
  </div>
  <div class="field">
    <%= f.label :lastname %><br>
    <%= f.text_field :lastname, :required => true %>
  </div>
  <div class="field">
    <%= f.label :address %><br>
    <%= f.text_field :address, :required => true %>
  </div>
  <div class="field">
    <%= f.label :mobile %><br>
    <%= f.text_field :mobile, :required => true %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.text_field :user_id, :required => true %>
  </div>
  <div class="actions">
  <span class="btn btn-default">  <%= f.submit %> </span>
  </div>
<% end %>
</div>

app/views/profiles/edit.html.erb
<h1>Editing profile</h1>

<%= render 'form' %>

app/views/profiles/index.html.erb
<h1>Listing profiles</h1>

<table>
  <thead>
    <tr>
      <th>Firstname</th>
      <th>Lastname</th>
      <th>Address</th>
      <th>Mobile</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @profiles.each do |profile| %>
      <tr>
        <td><%= profile.firstname %></td>
        <td><%= profile.lastname %></td>
        <td><%= profile.address %></td>
        <td><%= profile.mobile %></td>
        <td><%= profile.user %></td>
        <td><%= link_to 'Show', profile %></td>
        <td><%= link_to 'Edit', edit_profile_path(profile) %></td>
        <td><%= link_to 'Destroy', profile, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Profile', new_profile_path %>

app/views/profiles/new.html.erb
<h4 class="text-center">New profile</h4>

<%= render 'form' %>
<div class="text-center">
<span class="btn btn-default"><%= link_to 'Exit Registration', items_path %></span>
</div>

app/views/profiles/show.html.erb
<div style="width:200px; height:200px; background:#f5f5f5; margin:20px auto; padding:20px;" class=" text-center ">

<p id="notice"><%= notice %></p>


<p>
  <strong>Firstname:</strong>
  <%= @profile.firstname %>
</p>

<p>
  <strong>Lastname:</strong>
  <%= @profile.lastname %>
</p>

<p>
  <strong>Address:</strong>
  <%= @profile.address %>
</p>

<p>
  <strong>Mobile:</strong>
  <%= @profile.mobile %>
</p>
</div>


<div class="text-center">




<%= link_to 'Create Profile', items_path, :class => "btn btn-default active   space btn-xs" %>


</div>