config/routes.rb
Rails.application.routes.draw do

  resources :reviews

  resources :contacts

  get 'white/index'

  devise_for :installs
  resources :orders do
  resources :orderitems
  end
  
  devise_for :users do
  resources :orders
  end
  

  get 'orderitems/index'

  get 'orderitems/show'

  get 'orderitems/new'

  get 'orderitems/edit'

  resources :profiles

  get 'review/index'
  get 'review/show'
  get 'review/new'
  get 'review/edit'

  resources :reviews


get '/home' =>'home#index'
get '/red' => 'red#index'
get '/white' => 'white#index'
get '/contact' => 'site#contact'
get '/myprofile' => 'profiles#myprofile' 
get '/about' => 'site#about'
get '/contact' => 'site#contact'
get '/Admin'=> 'user#admin_login'
get '/payment' => 'cart#payment'
get '/cart' => 'cart#index'
get '/cart/clear' => 'cart#clearCart'
get '/cart/:id' => 'cart#add'
get '/cart/remove/:id' => 'cart#remove'
get '/checkout' => 'cart#createOrder'
resources :items


# config/routes.rb
get "/404", :to => "errors#not_found"
get "/422", :to => "errors#unacceptable"
get "/500", :to => "errors#internal_error"


 root :to => 'home#index'
  
end

app/models/contact.rb
class Contact < ActiveRecord::Base
end

app/models/install.rb
class Install < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/item.rb
class Item < ActiveRecord::Base
	has_many :reviews
end

app/models/order.rb
class Order < ActiveRecord::Base
  has_many :orderitems
  belongs_to :user
end

app/models/orderitem.rb
class Orderitem < ActiveRecord::Base
  belongs_to :order
end

app/models/profile.rb
class Profile < ActiveRecord::Base
  belongs_to :user
end

app/models/review.rb
class Review < ActiveRecord::Base


  belongs_to :item

  	


end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

     has_many :orders   
     has_one :profile
     has_many :reviews
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
# GET /items
# GET /items.json
before_filter :authenticate_user!
before_filter :ensure_admin, :only => [:new, :create, :edit, :destroy]
before_action :set_item, only: [:show, :edit, :update,:destroy]
  def ensure_admin
  unless current_user && current_user.admin?
  render:text => "Access Error", :status => :unauthorized
  end
  end 

  # GET /items
  # GET /items.json
  def index
    @items = Item.all
  end


  # GET /items/1
  # GET /items/1.json
  def show
    
  end

  # GET /items/new
  def new
    @item = Item.new
  end

  # GET /items/1/edit
  def edit
  end

  # POST /items
  # POST /items.json
  def create
    @item = Item.new(item_params)

    respond_to do |format|
      if @item.save
        format.html { redirect_to @item, notice: 'Item was successfully created.' }
        format.json { render :show, status: :created, location: @item }
      else
        format.html { render :new }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /items/1
  # PATCH/PUT /items/1.json
  def update
    respond_to do |format|
      if @item.update(item_params)
        format.html { redirect_to @item, notice: 'Item was successfully updated.' }
        format.json { render :show, status: :ok, location: @item }
      else
        format.html { render :edit }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1
  # DELETE /items/1.json
  def destroy
    @item.destroy
    respond_to do |format|
      format.html { redirect_to items_url, notice: 'Item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def item_params
      params.require(:item).permit(:name, :price, :description, :image_ur, :img_url_big, :category)
    end
end

app/controllers/red_controller.rb
class RedController < ApplicationController

before_filter :authenticate_user!
before_filter :ensure_admin, :only => [:new, :create, :edit, :destroy]
before_action :set_item, only: [:show, :edit, :update,:destroy]
  def ensure_admin
  unless current_user && current_user.admin?
  render:text => "Access Error", :status => :unauthorized
  end
  end 

  def index
     @items = Item.where(category: 'Red')
  end

  

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def item_params
      params.require(:item).permit(:name, :price, :description, :image_ur, :img_url_big, :category)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_helper.rb
module CartHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/orderitems_helper.rb
module OrderitemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/red_helper.rb
module RedHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper

	
end

app/helpers/session_helper.rb
module SessionHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/white_helper.rb
module WhiteHelper
end

app/views/items/_form.html.erb
<%= form_for(@item) do |f| %>
  <% if @item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@item.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
      <% @item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field text-center">
    <%= f.label :name %><br>
   <%= f.text_field :name, :required => true %>
  </div>
  <div class="field text-center">
    <%= f.label :price %><br>
    <%= f.text_field :price ,:required => true%>
  </div>
  <div class="field text-center">
    <%= f.label :description %><br>
    <%= f.text_area :description ,:required => true%>
  </div>
  <div class="field text-center">
    <%= f.label :image_ur %><br>
    <%= f.text_field :image_ur ,:required => true%>
  </div>
  <div class="field text-center">
    <%= f.label :img_url_big %><br>
    <%= f.text_field :img_url_big ,:required => true%>
  </div>
  <div class="field text-center">
    <%= f.label :category %><br>
    <%= f.text_field :category ,:required => true%>
  </div>
  <div class="btn btn-default active  pull-right space btn-xs">
    <%= f.submit %>
  </div>
<% end %>

app/views/items/edit.html.erb
<div class="row"> 
  <div class="col-md-3"></div>
      <div class="col-md-6">

<br/>
<h4 class="text-center"><mark>Edit inventory</mark></h4><br/>
<%= render 'form' %>

<div><%= link_to 'Show Update', @item , :class => "btn btn-default btn-warning btn-sm" %> 
    <%= link_to 'Cancel Update', @item ,:class => "btn btn-default btn-warning btn-sm" %></div>
</div>
<div class="col-md-3"></div>
</div><!--end row-->

app/views/items/index.html.erb
<div class="row"> 
  <div class="col-md-1"></div>
      <div class="col-md-8">

          <%@items.each do |item| %> 
        
              <div class="solid_line">        
          <div class = "pull-left img-rounded item title disab"> <%= link_to(image_tag(item.image_ur, height: "170", width:"170"),item)%></div>
        

          <div class="name"><%= item.name %><br/></div>
          <div class="description text-muted center-block "><%= item.description %> 

          <%= link_to 'More information...', item, :class => "text-danger" %><br/><br/> </div>
                                                
          <div class="price"> <span style="color:#ca1e03">Price</span> <%= number_to_currency(item.price) %><br/></div>
        <% if current_user.admin? %>
         <div><%= link_to 'Show', item ,:class => "btn btn-warning  btn-sm"%></div>
          <% end %>

            <% if user_signed_in? & !current_user.admin?%>
            <a href="/cart/<%= item.id %>"><div class="cart"><button type="button" class="btn btn-warning btn-sm">Add to Cart</button></a><br></div>

           
            
          <% end %>

                <div class="clearfix"></div>
     </div>
          <% end %> 

</div>
<% if current_user.admin? %>
    <div class="col-md-2"><br/><br/>
    <p class="text-danger">Add new item?</p>    
    <div><%= link_to 'New Item', new_item_path, :class => "btn btn-warning active " %></a> </div>
    <% end -%>
</div>

    
      
      
  
       

 

app/views/items/new.html.erb
<div class="row"> 
  <div class="col-md-3"></div>
      <div class="col-md-6">

<br/>
<h4 class="text-center"><mark>Add new inventory</mark></h4><br/>
<br/>
<%= render 'form' %>

<div><%= link_to 'Return', items_path, :class => "btn btn-default active  pull-right space btn-xs" %></div>

</div>
<div class="col-md-3"></div>
</div><!--end row-->

app/views/items/show.html.erb
<div class="row"> 
  <div class="col-md-2"></div>
    <div class="col-md-8">
      <div class="solid_line" style="padding:20px;">   
            <br/>     
            <div class = "pull-left img-rounded disab"> <%= image_tag @item.img_url_big, height: "330", width:"140" %></div>
         

            <div class="name"><%= @item.name %><br/>
            </div>

            <div class="description text-muted center-block "><%= @item.description %> <br/><br/>
            </div>
          
            <div class="price text-center"> <span style="color:#ca1e03">Price</span> <%= number_to_currency(@item.price) %><br/><br/>
            </div>
             <% if current_user.admin? %>
          
         <div><%= link_to 'Edit', edit_item_path,:class => "btn btn-danger active btn-sm" %>
           
         <%= link_to 'Destroy', @item, :confirm => 'Are you sure?', :method => :delete ,:class => "btn btn-danger active btn-sm"%></div>
         
          <% end %>


             <% if user_signed_in? & !current_user.admin?%>
            <div class="text-center">
     <a href="/cart/<%= @item.id %>"> <span class="cart"><button type="button" class="btn btn-warning btn-sm">Add to Cart</button></span></a>
  
      <% end %>

<br/>
      
          </div>

            <br/>
        <div>
      
      <%= link_to 'Product Review', reviews_path(id: @item.id), :class => "btn btn-warning active space btn-xs" %>
      

      <%= link_to 'Add new Review', new_review_path(id: @item.id, name: @item.name),:class => "btn btn-warning active space btn-xs"%>

        <%= link_to 'Return', items_path, :class => "btn btn-warning active btn-xs space" %>
        <br/><br/>
        </div>
        
        <br/>
        
      </div>
    </div>
  </div>  
</div>