config/routes.rb
Rails.application.routes.draw do

  resources :reviews

  resources :contacts

  get 'white/index'

  devise_for :installs
  resources :orders do
  resources :orderitems
  end
  
  devise_for :users do
  resources :orders
  end
  

  get 'orderitems/index'

  get 'orderitems/show'

  get 'orderitems/new'

  get 'orderitems/edit'

  resources :profiles

  get 'review/index'
  get 'review/show'
  get 'review/new'
  get 'review/edit'

  resources :reviews


get '/home' =>'home#index'
get '/red' => 'red#index'
get '/white' => 'white#index'
get '/contact' => 'site#contact'
get '/myprofile' => 'profiles#myprofile' 
get '/about' => 'site#about'
get '/contact' => 'site#contact'
get '/Admin'=> 'user#admin_login'
get '/payment' => 'cart#payment'
get '/cart' => 'cart#index'
get '/cart/clear' => 'cart#clearCart'
get '/cart/:id' => 'cart#add'
get '/cart/remove/:id' => 'cart#remove'
get '/checkout' => 'cart#createOrder'
resources :items


# config/routes.rb
get "/404", :to => "errors#not_found"
get "/422", :to => "errors#unacceptable"
get "/500", :to => "errors#internal_error"


 root :to => 'home#index'
  
end

app/models/contact.rb
class Contact < ActiveRecord::Base
end

app/models/install.rb
class Install < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/item.rb
class Item < ActiveRecord::Base
	has_many :reviews
end

app/models/order.rb
class Order < ActiveRecord::Base
  has_many :orderitems
  belongs_to :user
end

app/models/orderitem.rb
class Orderitem < ActiveRecord::Base
  belongs_to :order
end

app/models/profile.rb
class Profile < ActiveRecord::Base
  belongs_to :user
end

app/models/review.rb
class Review < ActiveRecord::Base


  belongs_to :item

  	


end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

     has_many :orders   
     has_one :profile
     has_many :reviews
end

app/controllers/red_controller.rb
class RedController < ApplicationController

before_filter :authenticate_user!
before_filter :ensure_admin, :only => [:new, :create, :edit, :destroy]
before_action :set_item, only: [:show, :edit, :update,:destroy]
  def ensure_admin
  unless current_user && current_user.admin?
  render:text => "Access Error", :status => :unauthorized
  end
  end 

  def index
     @items = Item.where(category: 'Red')
  end

  

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def item_params
      params.require(:item).permit(:name, :price, :description, :image_ur, :img_url_big, :category)
    end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
 before_filter :authenticate_user!
  before_action :set_review, only: [:show, :edit, :update, :destroy]



  respond_to :html 

  def index
    id = params[:id]
     @reviews = Review.where(user_id: id)

    end

  def show
    respond_with(@reviews)
  end

  def new
     @review = Review.new
    id = params[:id]
    name = params[:name]
  @review.user_id = id
  @review.productname = name
    
    respond_with(@review)
  end

  def edit
  end

  def create
    review_params[:reviwtext] = ProfanityWords.swapProfanity(review_params[:reviwtext] )
    @review = Review.new(review_params)

    @review.save
    respond_with(@review)
  end

  def update
    review_params[:reviwtext] = ProfanityWords.swapProfanity(review_params[:reviwtext] )
    @review.update(review_params)
    respond_with(@review)
  end

  def destroy
    @review.destroy
    respond_with(@review)
  end

  private
    def set_review

      @review = Review.find(params[:id])
      

    end

    def review_params
      params.require(:review).permit(:productname, :reviwtext, :itemrate, :user_id)
    end
end

app/helpers/cart_helper.rb
module CartHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/orderitems_helper.rb
module OrderitemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/red_helper.rb
module RedHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper

	
end

app/helpers/session_helper.rb
module SessionHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/white_helper.rb
module WhiteHelper
end

app/views/reviews/_form.html.erb
<div class="row"> 
  <div class="col-md-3"></div>
      <div class="col-md-6"><br/>



<%= form_for(@review) do |f| %>
  <% if @review.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@review.errors.count, "error") %> prohibited this review from being saved:</h2>

      <ul>
      <% @review.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<div class="field" style="display:none">
    <%= f.label :user_id,"User Id" %><br>
    <%= f.text_field :user_id, :required => true %>
  </div>
  
  


  <div class="field" style="display:none">
    <%= f.label :productname,"Wine Name"%><br>
    <%= f.text_field :productname , :required => true , :class => "input_n"%>
  </div>


  <div class="field" >
    <%= f.label:reviwtext ,"Your Review"%><br>
    <%= f.text_area :reviwtext , :required => true%>
  </div>
  <div class="field">
    <%= f.label :itemrate, "Satisfaction Rate" %><br>
    <%= f.number_field :itemrate, :required => true , :class => "input_f", min: "1" , max:"5" %>
  </div>



  <div class="actions">
 <%= f.submit "Submit", class: "btn btn-warning active btn-xs" %>
  </div>
<% end %>


</div>
</div>

app/views/reviews/edit.html.erb
<div class="row"> 
  <div class="col-md-3"></div>
      <div class="col-md-6"><br/>


<h4 class="text-center"><mark>Edit Review</mark></h4><br/>
<%= render 'form' %>

<%= link_to 'Show', @review ,:class => "btn btn-warning active  pull-right space btn-xs" %> 
<%= link_to 'Back', reviews_path, :class => "btn btn-warning active  pull-right space btn-xs"  %>
</div>
</div>

app/views/reviews/index.html.erb
<div class="row"> 
  <div class="col-md-1"></div>
   <div class="col-md-10">
<br/>
<h4 class="text-center"><mark>Wine reviews</mark></h4><br/>
<br/>




<table class="table table-striped table-bordered">
  <thead>
    <tr>
      <th>Wine-Name</th>
      <th>Wine-Reviews</th>
      <th>Customer Rate</th>

    </tr>
  </thead>

  <tbody>
    <% @reviews.each do |review| %>
      <tr class="warning">
        <td><%= review.productname %></td>
        <td><%= review.reviwtext %></td>
        <td><%= review.itemrate %></td>
        
         <% if current_user.admin?%>
        <td><%= link_to 'Show', review , :class => "btn btn-default active   space btn-xs"%></td>
        <td><%= link_to 'Edit', edit_review_path(review), :class => "btn btn-default active   space btn-xs" %></td>
        <td><%= link_to 'Destroy', review, method: :delete, data: { confirm: 'Are you sure?' }, :class => "btn btn-default active   space btn-xs" %></td>
        <% end%>
      </tr>
      
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Return', items_path, :class => "btn btn-warning active  pull-right space btn-xs" %>

</div>
<div class="col-md-1"></div>
</div>

app/views/reviews/new.html.erb
<div class="row"> 
  <div class="col-md-3"></div>
      <div class="col-md-6"><br/>


<h4 class="text-center"><mark>New review</mark></h4><br/>
<div class="text-center">
<%= render 'form' %>
</div>
<%= link_to 'Cancel', items_path,:class => "btn btn-warning active  pull-right btn-xs" %>

</div>
</div>

app/views/reviews/show.html.erb
<div class="row"> 
  	<div class="col-md-3"></div>
      <div class="col-md-6"><br/>
		<span class="text-center"><h4><mark>Wine Review</mark></h4><span><br/>

		<p id="notice"><%= notice %></p>

		<p>
  		<strong>Wine Name:</strong>
  		<%= @review.productname %>
		</p>

	<p>
  	<strong>Wine Review:</strong>
  	<%= @review.reviwtext %>
	</p>

	<p>
  	<strong>Satisfaction Rate:</strong>
  	<%= @review.itemrate %>
	</p><br/>
	<% if current_user.admin?%>
	<div ><%= link_to 'Edit', edit_review_path(@review), :class => "btn btn-warning active btn-xs" %>
	<%end%>
	<%= link_to 'Return', items_path , :class => "btn btn-warning  active btn-xs pull-right"%><br/><br/>
	</div>
	</div>
</div